### ISSUE TITLE
0.18.2: Error: Cannot find module 'core-js/modules/es6.promise'

### ISSUE THREAD

**Issue by orrgal1** [dashersw/cote#144]
Getting this in 0.18.2
Downgraded to 0.18.0 to resolve
Have not checked 0.18.1

Error: Cannot find module 'core-js/modules/es6.promise'
module.js:547
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/development/accs-messaging/node_modules/cote/dist/components/requester.js:3:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/development/accs-messaging/node_modules/cote/dist/index.js:5:19)

**Comment by dashersw** [comment]
Thank you, fixed!
