### ISSUE TITLE
Socket error

### ISSUE THREAD

**Issue by dreambit** [dashersw/cote#200]
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND bro-ms-pc565 bro-ms-pc565:8000
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
Emitted 'error' event at:
    at Socket.<anonymous> (C:\projects\photon\node_modules\@dashersw\axon\lib\sockets\sock.js:199:49)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

How to handle socket errors?

**Comment by dashersw** [comment]
For requester, responder, publisher or subscriber you can do `this.sock.on('error' cb)`.

**Comment by dreambit** [comment]
@dashersw What about redis error?
How to handle it?
Thanks

**Comment by dashersw** [comment]
@dreambit it's a little tricky, but you can access it through `requester.discovery.broadcast.socket.sub.on('error', err => console.log(err))` where `requester` is any cote component.
