### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: cb is not a function

### ISSUE THREAD

**Issue by JeanDenisVIDOT** [dashersw/cote#91]
Hello,

I want to return promise instead of using callback as parameter : 

Requester side :

```javascript
import * as cote from 'cote';

const tutuRequester = new cote.Requester({ name: 'Tutu Requester'});

tutuRequester.send({ type: 'foo' })
  .then(data => console.log('tutu received:', data))
  .catch(console.error);
```

Responder side: 

```javascript
import * as cote from 'cote';

const userService = new cote.Responder({ name: 'User Service Responder'});

userService.on('*', (req: {}) => {
  const answer = ~~(Math.random() * 10);

  return new Promise((resolve) => {
    console.log('promise request', req, 'answering with', answer);
    resolve(answer);
  });
});
```
But I'm getting this error : 

```
user_service_1  | (node:84) UnhandledPromiseRejectionWarning: TypeError: cb is not a function
user_service_1  |     at /app/node_modules/cote/src/components/responder.js:45:34
user_service_1  |     at <anonymous>
user_service_1  |     at process._tickCallback (internal/process/next_tick.js:182:7)
user_service_1  | (node:84) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
user_service_1  | (node:84) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

PS : I'm using typescript

Kind regards

**Comment by dashersw** [comment]
The problem is you're using `'*'` to listen to all events — but there are some internal events that are also triggered like `added` and `removed`. You can easily fix this by listening on `'foo'`. Or you can ignore the messages that don't have a `type` attribute.

In your event handler, simply add the following:
```js
if (!req.type) return;
```

and now you're able to use `'*'` again.

**Comment by JeanDenisVIDOT** [comment]
Ok I understand :). Thanks for your help !

**Comment by jessety** [comment]
Hello, 

I wasn't sure if I should open a new issue or not, but I tried the solution recommended here and it didn't work as of version `1.0.0`.

Example: 
```javascript
const cote = require('cote');

// Create a requester and handle incoming requests

const responder = new cote.Responder({ name: 'Example Responder' });

responder.on('*', async request => {

  if (!request.type) {
    return;
  }

  console.log('Got a request!');
  return Math.floor(Math.random() * 100);
});

// Wait a second, then make a requester and send a request

setTimeout(async () => {

  console.log(`Sending request`);

  const requester = new cote.Requester({ name: 'Example Requester' });

  try {
    const response = await requester.send({ type: 'question' });
    console.log(`Got response`, response);
  } catch (error) {
    console.error(`Caught error making request`, error);
  }

  process.exit();

}, 1000);
```

The above code triggers this error: 
```
(node:3769) UnhandledPromiseRejectionWarning: TypeError: cb is not a function
    at .../cote_test/node_modules/cote/src/components/responder.js:52:34
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

It was relatively easy to work around this by creating an array of all expected event types and listening for them specifically: 
```javascript
for (const type of requestTypes) {
  this.responder.on(type, request => handle(request));
}
```

Still, I was wondering if there's newer way to ignore internal events.

Thank you!

**Comment by dashersw** [comment]
oh this is very helpful! I will fix this soon.
